# Configuración específica para Bybit
bybit:
  enabled: true
  # Parámetros de conexión (usar credenciales de testnet para pruebas)
  api_key: ""  # Dejar vacío para modo de solo datos (no trading)
  secret: ""   # Dejar vacío para modo de solo datos (no trading)
  testnet: true  # Usar testnet para pruebas
  
  # Configuración de datos
  default_symbol_list:
    - "BTC/USDT"
    - "ETH/USDT"
    - "SOL/USDT"
    - "BNB/USDT"
    - "ADA/USDT"
    - "XRP/USDT"
  
  # Timeframes predeterminados
  default_timeframe: "1h"
  timeframes:
    - "15m"
    - "1h"
    - "4h"
    - "1d"
  
  # Rango de fechas predeterminado
  start_date: "2025-08-01"
  end_date: "2025-09-01"
  
  # Opciones de descarga
  rate_limit: true  # Respetar límites de tasa de la API
  retry_on_error: true  # Reintentar en caso de error
  max_retries: 3  # Número máximo de reintentos
  retry_delay: 5  # Tiempo de espera entre reintentos (segundos)
