active_exchange: binance
backtesting:
  commission: 0.1
  data_quality: null
  end_date: '2025-10-16'
  initial_capital: 500
  optimized_parameters:
    BTC_USDT:
      atr_period: 11
      cci_threshold: 140
      ema_trend_period: 100
      kelly_fraction: 0.25
      max_concurrent_trades: 7
      max_drawdown: 0.05
      max_portfolio_heat: 0.14
      ml_threshold: 0.2
      ml_threshold_min: 0.4
      ml_threshold_max: 0.75
      sar_acceleration: 0.19
      sar_maximum: 0.13
      stoch_overbought: 65
      stoch_oversold: 30
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 4.25
      volume_ratio_min: 0.4
  slippage: 0.05
  start_date: '2025-01-01'
  strategies:
    UltraDetailedHeikinAshiML: true
  strategy_paths:
    UltraDetailedHeikinAshiML:
    - strategies.ultra_detailed_heikin_ashi_ml_strategy
    - UltraDetailedHeikinAshiMLStrategy
  symbol_selection:
    BTC/USDT: true
  symbols:
  - BTC/USDT
  timeframe: 15m
compensation_strategy:
  compensation_max_loss: 1.0
  emergency_stop_buffer: 0.8
  enabled: true
  loss_threshold: 0.5
  max_account_drawdown: 3.0
  risk_multiplier_high_dd: 0.7
  size_multiplier: 3.0
  tp_percent: 0.5
data:
  limit_per_request: 1000
  max_retries: 3
  retry_delay: 5
  use_ccxt_for_crypto: true
  use_mt5_for_stocks: false
  validate_data: true
exchanges:
  binance:
    api_key: ''
    api_secret: ''
    enabled: true
    sandbox: true
    timeout: 30000
  bybit:
    api_key: ''
    api_secret: ''
    enabled: true
    sandbox: true
    timeout: 30000
indicators:
  adx:
    enabled: true
    period: 14
    threshold: 25
  atr:
    enabled: true
    period: 14
  ema:
    enabled: true
    periods:
    - 10
    - 20
    - 200
  heikin_ashi:
    enabled: true
    size_comparison_threshold: 1.2
    trend_period: 3
  parabolic_sar:
    acceleration: 0.02
    enabled: true
    maximum: 0.2
  volatility:
    enabled: true
    method: standard_deviation
    period: 14
live_trading:
  account_type: DEMO
  active_strategy: Solana4HRiskManaged
  active_symbol: BTC/USDT
  apply_risk_management: true
  ccxt_exchange: bybit
  ccxt_symbols:
  - BTC/USDT
  - ETH/USDT
  - SOL/USDT
  ccxt_timeframes:
  - 1h
  - 4h
  enabled: false
  initial_history_bars: 1000
  max_positions: 5
  max_positions_per_symbol: 1
  mode: MT5
  mt5_symbols:
  - EURUSD
  - USDJPY
  - XAUUSD
  mt5_timeframes:
  - 1h
  - 4h
  - 1d
  risk_per_trade: 0.01
  strategy_mapping: {}
  update_interval_seconds: 5
  validation: {}
ml_training:
  enabled_models:
    random_forest: true
  models:
    random_forest:
      max_depth: 10
      n_estimators: 100
      n_jobs: 1
      random_state: 42
  optimization:
    enabled: true
    n_trials: 100
    opt_end: '2025-10-16'
    opt_start: '2025-07-01'
    study_name: btc_ml_optimization_v3
  safe_mode: false
  training:
    min_samples: 500
    train_end: '2022-12-31'
    train_start: '2020-01-01'
    val_end: '2023-12-31'
    val_start: '2023-01-01'
mt5:
  enabled: false
  login: 0
  password: ''
  server: ''
  terminal_path: ''
  timeout: 60000
reports:
  generate_comparison: true
  output_directory: backtest_results
  save_equity_curves: true
  save_individual_results: true
  save_trade_details: true
risk:
  max_drawdown_limit: 15.0
  risk_percent: 0.5
  sl_atr_multiplier: 1.5
  tp_atr_multiplier: 2.0
storage:
  cache_enabled: true
  csv_enabled: true
  path: data
  sqlite_enabled: true
system:
  auto_launch_dashboard: true
  log_file: logs/bot_trader.log
  log_level: INFO
  name: Bot Trader Copilot
  version: 3.0