active_exchange: bybit
backtesting:
  commission: 0.1
  end_date: '2023-12-31'
  initial_capital: 10000
  strategies:
    Estrategia_Basica: false
    Estrategia_Compensacion: false
    DeepAnalysis: false
    HeikinAshiVolumenSar: false
    HeikinAshiVolumenSarImproved: false
    Solana4H: false
    Solana4HSAR: false
    UltraDetailedHeikinAshi: false  # Desactivada - archivo no existe
    OptimizedStrategy: false
    EstrategiaGaadors: true  # Activada - estrategia principal con ML
  optimized_parameters:
    BTC/USDT:
      4h:
        ml_threshold: 0.3  # MUY PERMISIVO - más señales (antes 0.8)
        stoch_overbought: 85  # Más permisivo
        stoch_oversold: 15  # Más permisivo
        cci_threshold: 80  # Más bajo para más señales
        volume_ratio_min: 0.3  # ULTRA PERMISIVO - más entradas (antes 1.2)
        sar_acceleration: 0.02  # Conservador
        sar_maximum: 0.2  # Conservador
        atr_period: 14  # Estándar
        stop_loss_atr_multiplier: 2.0  # Conservador
        take_profit_atr_multiplier: 3.0  # Conservador
        ema_trend_period: 50  # Estándar
        max_drawdown: 0.08  # Más tolerante (antes 0.05)
        max_portfolio_heat: 0.06  # Más agresivo (antes 0.04)
        max_concurrent_trades: 5  # Más oportunidades (antes 2)
        kelly_fraction: 0.5  # Más agresivo (antes 0.3)
        liquidity_score_min: 5  # MUY PERMISIVO (antes 10)
    DOGE/USDT:
      4h:
        atr_period: 14
        atr_volatility_threshold: 2.0
        ema_trend_period: 50
        max_consecutive_losses: 3
        min_trend_strength: 0.5
        sar_acceleration: 0.02
        sar_maximum: 0.15
        stop_loss_atr_multiplier: 2.0
        take_profit_percent: 3.0
        trailing_stop_atr_multiplier: 1.5
        volatility_filter_threshold: 0.03
        volume_sma_period: 20
        volume_threshold: 1000
    SOL/USDT:
      4h:
        atr_period: 14
        atr_volatility_threshold: 2.0
        ema_trend_period: 50
        max_consecutive_losses: 3
        min_trend_strength: 0.5
        sar_acceleration: 0.02
        sar_maximum: 0.15
        stop_loss_atr_multiplier: 2.0
        take_profit_percent: 3.0
        trailing_stop_atr_multiplier: 1.5
        volatility_filter_threshold: 0.03
        volume_sma_period: 20
        volume_threshold: 1000
    XRP/USDT:
      4h:
        atr_period: 14
        atr_volatility_threshold: 2.0
        ema_trend_period: 50
        max_consecutive_losses: 3
        min_trend_strength: 0.5
        sar_acceleration: 0.02
        sar_maximum: 0.15
        stop_loss_atr_multiplier: 2.0
        take_profit_percent: 3.0
        trailing_stop_atr_multiplier: 1.5
        volatility_filter_threshold: 0.03
        volume_sma_period: 20
        volume_threshold: 1000
    AVAX/USDT:
      4h:
        atr_period: 14
        atr_volatility_threshold: 2.0
        ema_trend_period: 50
        max_consecutive_losses: 3
        min_trend_strength: 0.5
        sar_acceleration: 0.02
        sar_maximum: 0.15
        stop_loss_atr_multiplier: 2.0
        take_profit_percent: 3.0
        trailing_stop_atr_multiplier: 1.5
        volatility_filter_threshold: 0.03
        volume_sma_period: 20
        volume_threshold: 1000
    SUSHI/USDT:
      4h:
        atr_period: 14
        atr_volatility_threshold: 2.0
        ema_trend_period: 50
        max_consecutive_losses: 3
        min_trend_strength: 0.5
        sar_acceleration: 0.02
        sar_maximum: 0.15
        stop_loss_atr_multiplier: 2.0
        take_profit_percent: 3.0
        trailing_stop_atr_multiplier: 1.5
        volatility_filter_threshold: 0.03
        volume_sma_period: 20
        volume_threshold: 1000
  slippage: 0.05
  start_date: '2022-01-01'
  strategies:
    Estrategia_Basica: false
    Estrategia_Compensacion: false
    DeepAnalysis: false
    HeikinAshiVolumenSar: false
    HeikinAshiVolumenSarImproved: false
    Solana4H: false
    Solana4HSAR: false
    UltraDetailedHeikinAshi: true
  symbols:
  - BTC/USDT
  timeframe: 4h
compensation_strategy:
  compensation_max_loss: 0.3
  emergency_stop_buffer: 0.98
  enabled: true
  loss_threshold: 0.2
  max_account_drawdown: 25.0
  size_multiplier: 1.5
  tp_percent: 0.25
exchanges:
  binance:
    api_key: ''
    api_secret: ''
    enabled: true
    sandbox: false
    timeout: 30000
  bybit:
    api_key: ''
    api_secret: ''
    enabled: true
    sandbox: false
    timeout: 30000
indicators:
  adx:
    enabled: true
    period: 14
    threshold: 25
  atr:
    enabled: true
    period: 14
  ema:
    enabled: true
    periods:
    - 10
    - 20
    - 200
  heiken_ashi:
    enabled: true
    size_comparison_threshold: 1.2
    trend_period: 3
  parabolic_sar:
    acceleration: 0.02
    enabled: true
    maximum: 0.2
  volatility:
    enabled: true
    period: 14
mt5:
  enabled: true
  login: 61406481
  password: Jatr280371$
  server: Pepperstone-Demo
  terminal_path: ''
  timeout: 60000
risk:
  max_drawdown_limit: 30.0
  risk_percent: 2.0
  sl_atr_multiplier: 1.5
  tp_atr_multiplier: 2.0
storage:
  cache_enabled: true
  csv_enabled: true
  path: descarga_datos/data
  sqlite_enabled: true
system:
  auto_launch_dashboard: true
  log_file: logs/bot_trader.log
  log_level: INFO
  name: Bot Trader Copilot
  version: 2.6.0

# Configuración de Machine Learning
ml_training:
  # Modo agresivo para maximizar P&L con drawdown 5-10%
  safe_mode: true  # ACTIVADO para compatibilidad Python 3.13

  # Modelos ML activados para optimización
  enabled_models:
    random_forest: true          # Activado para optimización
    gradient_boosting: false     # Mantenido desactivado por estabilidad
    neural_network: false        # Mantenido desactivado por estabilidad

  # Parámetros de entrenamiento
  training:
    train_start: '2020-01-01'    # Inicio período entrenamiento
    train_end: '2023-12-31'      # Fin período entrenamiento
    val_start: '2024-01-01'      # Inicio validación
    val_end: '2024-12-31'        # Fin validación
    min_samples: 1000            # Mínimo velas para entrenamiento

  # Parámetros de modelos
  models:
    random_forest:
      n_estimators: 100
      max_depth: 10
      n_jobs: 1  # Importante para Python 3.13 - evitar problemas de paralelismo
      random_state: 42
    gradient_boosting:
      n_estimators: 100
      max_depth: 3
      learning_rate: 0.1
      random_state: 42
    neural_network:  # XGBoost
      n_estimators: 100
      max_depth: 4
      learning_rate: 0.1
      eval_metric: 'logloss'
