# Configuración específica para MetaTrader 5
mt5:
  enabled: true
  # Parámetros de conexión
  terminal_path: ""  # Dejar vacío para usar el terminal predeterminado
  server: ""  # Nombre del servidor de trading (dejar vacío para usar el predeterminado)
  login: 0  # ID de login (0 para modo invitado)
  password: ""  # Contraseña (vacío para modo invitado)
  timeout: 60000  # Tiempo de espera para operaciones (ms)
  
  # Configuración de datos
  default_symbol_list:
    - "EURUSD"
    - "USDJPY"
    - "GBPUSD"
    - "AUDUSD"
    - "AAPL.US"  # Apple
    - "MSFT.US"  # Microsoft
    - "TSLA.US"  # Tesla
  
  # Timeframes predeterminados
  default_timeframe: "1h"
  timeframes:
    - "15m"
    - "1h"
    - "4h"
    - "1d"
  
  # Rango de fechas predeterminado
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  
  # Opciones de descarga
  use_real_volume: true  # Si es false, usa tick_volume
  max_bars: 10000  # Máximo número de barras a descargar por solicitud
